### PR TITLE
added the option to set reference dir in hash manifest

### PR DESCRIPTION
**Pull request by didiercrunch**
Hi there,

I wanted to do something simple but was not able.  I had a file structure with all my js files in a `js/` directory and used your gulp-hash to add a hash to the files and move them into a `dist/` directory.  I wanted a manifest file like `{"js/foo.js": "dist/foo.js"}` and was not able.

Consequently I added a options parameter to the manifest function.  If the option has a `base` field, it use it as reference directory for the manifest file.

I am not sure you want this feature in your package.  It does not break backward compatibility.

### CODE REVIEW

**Comment by Dragory** [comment]
Hey, sorry for the delayed response! If I'm not mistaken, this seems like a task for [gulp-rename](https://www.npmjs.com/package/gulp-rename). The way I would do it is rename the original file to "js/foo.js" before hashing and then rename the hashed file afterwards. Something like this (untested):

```javascript
gulp.src('src/**/*.js', {base: 'src'})
    .pipe(rename(function(p) {
        // Prepend js/ to original dirname (keeping directory structure inside src)
        p.dirname = 'js/' + p.dirname;
    }))
    .pipe(hash())
    .pipe(rename(function(p) {
        // Replace the js/ at the start of dirname with dist/
        p.dirname = p.dirname.replace(/^js\//g, 'dist/');
    }))
    // Files will be written to dirname, hence just '.' here to write under 'dist'
    .pipe(gulp.dest('.'));
```

Can you give it a try?

**Comment by werts** [comment]
Hi there.
that sounds great to use this plugins,However, i want to use it to hash my files and use via seajs config.all my projects' seajs configs have no extension,it seems like that:{jquery:"wxwebapp2.0/jquery.min"}, but the hash map after files hashed contains extension, so could i wrap your plugins or pull my request?i have done this locally

**Comment by jorrit** [comment]
Using gulp-rename doesn't work because gulp-hash uses the path from the output file as the key of the manifest file. So when original file src/x.js is hashed as dist/x.abc.js, the manifest will show `"dist/x.js": "dist/x.abc.js"` instead of `"src/x.js": "dist/x.abc.js"`. See my PR #17 for a fix.

**Comment by Dragory** [comment]
This was fixed by @jorrit's pull request #17, correct? You should now be able to use gulp-rename for this.

**Pull request closed without merging**
